name: Continuous Deployment Pipeline

on:
  push:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
  deploy-development:
    name: Deploy Development
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/environments/development
    needs:
      - ci
    environment: 
      name: development
      url: https://app.terraform.io/app/Cantonite/workspaces/terraform-deployment-pipeline-development
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file=../../.github/workflows/data/environments/development.json