name: Terraform Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: The name of the environment being deployed to
        required: false
        type: string
    secrets:
        terraform_api_token:
          required: false

jobs:
  terraform-deploy:
    name: Deploy ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      TF_WORKSPACE: ${{ inputs.environment }}
      TF_IN_AUTOMATION: true
    environment:
      name: ${{ inputs.environment }}
      url: https://app.terraform.io/app/Cantonite/workspaces/terraform-deployment-pipeline-${{ inputs.environment }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.environment }}-terraform-build
      - name: Extract Tar
        id: tar
        run: tar -xvf ${{ inputs.environment }}.tar
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.terraform_api_token }}
      - name: Terraform Apply
        id: apply
        run: terraform apply -input=false ${{ inputs.environment }}.tfplan
